<h1>Super Visa Insurance</h1>

<p>Super Visa which came into effect in December 2011 and is becoming super popular among landed immigrants and Canadian citizens is a golden opportunity for family reunion. This Super Visa as we are aware is a multiple entry visa which is valid for 10 year allowing parents and grandparents to visit and stay in Canada for up to two years in a stretch without the need to renew it every time. The process for getting a Parents and Grandparents Super Visa is simple and straightforward. Applicants for the Super Visa must provide proof that the host child or grandchild meets a minimum income level, demonstrate that they have purchased comprehensive Canadian medical insurance and undergo the immigration medical examination.<br>
  Statistics reveal that majority of the parents don't actually want to immigrate to Canada; they just want to visit loved ones on a regular basis. Parents visiting Canada under the Super visa category are overwhelmed with Super Visa as it has given an alternative for reunion with loved ones. All those parents who are still waiting for their prolonged immigration process are relieved with this super visa opportunity. The super visa could be a bridge from now until the permanent resident is accepted. So if the permanent resident process could take three to four years, then the super visa could act as a bridge.<br>
  Shiv Financial Services is committed to provide you lowest possible super visa insurance quotes with best protection to your parents and grandparents. Our dedication to superior client service has brought us to the Internet as we endeavour to continue to provide the highest quality professional service and guidance.   We offer best insurance rates to our clients by comparing all the benefits of different plans offered by different companies.</p>
<p>Comprises of people who are permanent residents or citizens of Canada who have arrived in Canada as immigrants and settled here for a quality life. We can understand the pain of separation from your parents or grandparents. We speak your language and can guide you in your doubts regarding super visa along with offering you the most affordable quotes than our competitors. As we are aware of the concept that one size does not fit all we offer wide range of policies which are suitable to your pockets. Apply today or call us- Cell-647-236-7620 for any queries or enquiries on super Visa.</p>
<p>When you apply for the Parent and Grandparent Super Visa, you must provide proof that you purchased medical insurance coverage (known as Super Visa insurance, Super Visa Medical Insurance, Super Visa Health Insurance) from a Canadian insurance company. The Super Visa insurance coverage must: <br>
  •	Be valid for a minimum period of one year from the date of entry to Canada<br>
  •	Provide a minimum of $100,000 coverage<br>
  •	Must cover health care, hospitalization and repatriation costs (the costs to return you to your home country, if necessary)<br>
  •	Each parent or grandparent must have insurance coverage. The policy must be valid for each entry to Canada, and must be readily available for review by point of entry officers.</p>
<p>On December 1st, 2011, the conservative government had finally come with an impressive plan of a new type of visa called the “Super Visa “for parents and grandparents of immigrants and Canadian citizens. This plan was initiated with a motive of clearing the vast backlog of about 165,000 parents and grandparents who are trying to join family in Canada. Parents and grandparents aspiring to visit their loved ones in Canada after applying are granted a 10 years visa which will have to be renewed after a period of 2 years. The main concern of the government is that the applicants wanting to apply for Super Visa is that they or their children who are sponsoring them will have to purchase a private Canadian health insurance, a basic plan that covers each parent up to $ 100,000 during their stay in Canada. Individuals sponsoring their parent or grandparent will have to show they can support their visiting relatives. When the NDP Critic criticized the government’s policy and commented that people who have applied for permanent residencies will be denied visa on the ground that they will not return back to their home country after landing in Canada. The government however made it clear that those who have applied for permanent residencies will be granted visa if the conditions are satisfied by the applicant.<br>
  Immigration Minister Jason Kenney says that won't be a problem — people who have applied for permanent residency will definitely be eligible for the visa. The immigration department has also stated that the actual rate of acceptance is going to be very high. The minister has also made it clear that the new health insurance requirement may make it easier for visa officers to say &quot;yes.&quot; So with the Super Visa effective from today i.e. December 1st, 2011 is a golden opportunity to all the immigrants and Canadian citizens to reunite with their loved ones. Shiv Financial Services supports applicants aspiring to visit their loved ones by offering affordable quotes. We understand your language and your sentiments allow us to serve you with the right plan.<br>
  Eligibility for applying under super visa category:<br>
  To apply for the Parent and Grandparent Super Visa, you must:<br>
  •	be the parent or grandparent of a Canadian citizen or a permanent resident of Canada;<br>
  •	be found admissible to Canada; and<br>
  •	Meet certain other conditions.<br>
  More Information<br>
  Visa officers consider several factors before deciding if a person is admissible. The person must be a genuine visitor to Canada who will leave by choice at the end of the visit. Among the things that could be considered are:<br>
  •	&gt; the person's ties to the home country;<br>
  •	&gt; the purpose of the visit;<br>
  •	&gt; the person's family and financial situation;<br>
  •	&gt; the overall economic and political stability of the home country; and<br>
  •	&gt; An invitation from a Canadian host.<br>
  In addition to being found admissible to Canada, the parent/grandparent must also:<br>
  •	- provide a written commitment of financial support from their child or grandchild in Canada who meets a minimum income threshold,<br>
  •	- prove that they have bought Canadian medical insurance for at least one year to cover the period of time that they will be in Canada, and<br>
  •	- Complete an Immigration Medical Examination (IME).<br>
  According to the above quote from the government's website, proof of Canadian medical insurance is required. While this may change in the future to a list of approved international carriers, the guidance so far is for visitors to purchase visitors insurance from a Canadian company. Why the restriction? Canadian travel insurance companies are governed by the regulations in Canada, and the government probably feels safer that any claims will be paid for by a company they can regulate. The government doesn't want to be the one to have to pay any claims, or sue a company that doesn't pay out a claim. Hospital costs for visitors to Canada can amount to over $3,000 per day, and air ambulance charges to return you home could very easily be in the tens of thousands of dollars. We recommend $100,000 of medical insurance coverage if peace of mind is what you are after, and a higher amount if you are visiting from farther away, or more elderly. Any policy less than $50,000 will be subjecting the family to unnecessary financial burden.<br>
</p>
<p>There cannot be anything better than Super Visa for family reunification. As of December 1, 2011, the Canadian citizens and permanent residents have an option to invite their parents and grandparents to visit them on Super Visa. It is a multi-entry visa that provides multiple entries for a period up to 10 years. It allows parents and grandparents to remain in Canada for up to 24 months at a time without the need for renewal of their status. It provides them the opportunity to spend longer periods of time with their children.<br>
  Citizenship, Immigration and Multiculturalism Minister announced in July, 2013 that more than 20,000 Parent and Grandparent Super Visas had been issued since the program’s launch in December 2011. More than 1,000 Super Visas are issued every month. Super Visa applications had been approved with an overall approval rate of as high as 85 percent.<br>
  Besides other requirements, parents and grandparents are required to have comprehensive medical insurance from Canadian insurance company to cover the time they will be in Canada. The coverage amount should be $100,000 or more and should meet the requirement like health care, hospitalization, repatriation, etc. The coverage for “stable” pre-existing condition is available for most of the age groups. Pre-existing condition is defined as a medical condition, sickness or injury for which consultation, diagnosis and/or treatment has been sought from a physician or any other know condition for which consultation is not sought yet.<br>
  Policy is quickly created and confirmation is sent through email to the clients. You have to pay the premium upfront for 365 days. You are required to attach the insurance confirmation/documents with the Super Visa Application. There is total flexibility to change the effective date if the Visa Application is still in process. There is full refund of premium in case the Visa is denied. Copy of a refusal letter is required along with the request for the refund of the premium. Partial refund is available too if parents or grandparents return to their home country early, provided there is no claim on the policy. It is subject to the administration fee.<br>
  Various deductible options are available to lower the premium and to make it more affordable. You may save from 5% to 45% depending upon the amount of deductible and the insurance company. It is important to understand that deductible will be from each and every claim for most of the companies. It is advised to read and understand the policy/plan details of the insurance company regarding the list of benefits, eligibility, limitations, exclusions and other terms &amp; conditions.<br>
  Insurance company must be informed as soon as possible of any emergency medical treatment or hospitalization. They are available 24/7. Failure to do so may result in decreasing your insurance benefits.</p>
<p>&nbsp;</p>
<p>Visitors  to Canada Medical Insurance &amp;  New Immigrants Medical Insurance.<br>
  Couple of hundred dollars paid for the medical insurance can save you from a financial catastrophe. Medical insurance protects you from high cost of emergency medical care. A small slip and fall or even a flu could cost you thousands of dollars. Emergency departments in the hospitals charge thousands of dollars per day. Canadian residents who invite relatives or friends to Canada are responsible for their support. Hospitals and medical offices have legal right to collect unpaid bills from the person who sponsored a visitor in Canada. Without sufficient emergency medical insurance, you and your family would be responsible for these high costs, which can create a significant financial burden. Sometimes, the Department of Immigration and Citizenship may require you to purchase and maintain adequate medical insurance arrangements for the duration of your intended stay in Canada.<br>
  Medical Insurance is available for following persons (provided they meet other eligibility requirements too specified by the insurance company):<br>
  1.	Visitors to Canada including parents and grandparents;<br>
  2.	Returning Canadians who are not yet eligible for benefits under a government health insurance plan issued by a province or territory;<br>
  3.	Persons who are in Canada on a student or work visa; or<br>
  4.	New immigrants who are awaiting coverage by government health insurance from a province or territory.<br>
  Policy is quickly created and confirmation is sent through email to the clients before they take off. Coverage must be purchased before the departure from the home country or preferably before reaching Canada. Coverage can be purchased after the arrival in Canada too but a “waiting period” will apply for sickness coverage. Any sickness that manifests itself during the waiting period is not covered even if related expenses are incurred after the waiting period. Injury coverage will start right way.<br>
  Coverage is available from $10,000 to $300,000 for emergency medical care if a person is hospitalized. Besides that, the same plan covers fever, flu, cough, etc. and offers benefits like payment for doctor fee, prescription drugs, diagnostic services, paramedical services, ambulance services, emergency dental treatment, expenses related to death, accidental death and dismemberment, expenses for meals and hotel, visit to bedside if travelling alone, childcare expenses, etc. Coverage for “stable” pre-existing conditionis available for most of the age groups. Coverage for travel time to/from Canada and for side trips is provided by many insurance companies subject to certain conditions.<br>
  Various deductible options are available to lower the premium and to make it more affordable. You may save from 5% to 45% depending upon the amount of deductible and the insurance company. It is important to understand that deductible will be from each and every claim for most of the companies.<br>
  It is advised to read the policy/plan details of the insurance company thoroughly regarding the list of benefits, eligibility, limitations, exclusions and other terms &amp; conditions. Insurance company must be informed as soon as possible of any emergency medical treatment or hospitalization. They are available 24/7. Failure to do so may result in decreasing your insurance benefits. All original bills and receipts are required to be sent to the insurance company along with the Claim Form to get the reimbursement. Sometimes hospitals and insurance companies tie up for direct billing but it varies by individual case to case.</p>



<h1>Travel Insurance</h1>
<p>Travel can be an enriching and unforgettable experience. However, without proper travel insurance, a dream holiday could lead to financial ruin or even worse. Out-of-pocket costs for relatively minor emergencies can put a damper on the vacation, sometimes costing hundreds of dollar. A medical emergency can pose a serious threat to the overall financial well-being. A more severe emergency could affect long-term plans for education or retirement. There have even been instances where families have been forced to rely on their superannuation funds or in some cases sell their homes in order to raise the money to bring their loved ones home - all because they failed to purchase travel insurance. Travel insurance protects the assets and the net worth of a person.<br>
  Provincial health insurance plans will usually pay for a small portion of out-of-province medical costs, but will fall far short of the full cost. Employer plans or credit cards may offer travel insurance coverage, but it’s wise to compare benefits. Employment benefits may not cover all medical emergencies or may limit travel benefits. Credit cards often provide coverage for a shorter number of days or restrict the amount you can claim.<br>
  Travel insurance is not a one solution that fits to everyone. Premium depends on the age, trip length and health status. You can get good rates if you are healthy. The longer you’re away the bigger the risks and higher the premium. A casual traveler and a frequent traveler need different plans.<br>
  It is advised to read and understand the policy/plan details of the insurance company regarding the list of benefits, eligibility, limitations, exclusions and other terms &amp; conditions. It is important to understand if the pre-existing condition, if any, is covered or not and what are the fine prints, if it is covered, so that you are aware if the claim will be paid or not with respect to the emergency medical treatment for the pre-existing condition or anything related to or due to the pre-existing condition.<br>
  Insurance company must be informed as soon as possible of any emergency medical treatment or hospitalization. They are available 24/7. Failure to do so may result in decreasing your insurance benefits. All original bills and receipts are required to be sent to the insurance company along with the Claim Form to get the reimbursement. Sometimes hospitals and insurance companies tie up for direct billing but it varies by individual case to case.<br>
  Should an unfortunate event occur, the last thing you should be worrying about is whether you’ll have enough money to deal with such an emergency.<br>
  Policy is quickly created and confirmation is sent through email to the clients before they take off or leave the home province.<br>
</p>
